"""
Markdown Report Writer

Generates human-readable Markdown reports for chain analysis results.
Reports include:
  - File overview
  - Summary statistics (fee rates, script types, flagged counts)
  - Per-block sections with heuristic findings
  - Notable transactions

Output must be ≥ 1KB and contain sections: Summary, Block, Heuristic, Fee Rate
"""

from datetime import datetime, timezone


def generate_report(file_output):
    """
    Generate a complete Markdown report from the JSON output dict.

    Args:
        file_output: dict from json_writer.build_file_output()

    Returns:
        str: complete Markdown content
    """
    lines = []
    blk_file = file_output.get('file', 'unknown')
    block_count = file_output.get('block_count', 0)
    summary = file_output.get('analysis_summary', {})
    blocks = file_output.get('blocks', [])

    total_txs = summary.get('total_transactions_analyzed', 0)
    flagged = summary.get('flagged_transactions', 0)
    heuristics = summary.get('heuristics_applied', [])

    # === Header ===
    lines.append(f"# Chain Analysis Report: {blk_file}")
    lines.append("")
    lines.append(f"**Generated by Sherlock — Bitcoin Chain Analysis Engine**")
    lines.append("")

    # === File Overview ===
    lines.append("## File Overview")
    lines.append("")
    lines.append(f"| Property | Value |")
    lines.append(f"|---|---|")
    lines.append(f"| Source File | `{blk_file}` |")
    lines.append(f"| Blocks in File | {block_count} |")
    lines.append(f"| Total Transactions Analyzed | {total_txs} |")
    lines.append(f"| Flagged Transactions | {flagged} ({_pct(flagged, total_txs)}%) |")
    lines.append(f"| Heuristics Applied | {len(heuristics)} |")
    lines.append("")

    # === Summary Statistics ===
    lines.append("## Summary Statistics")
    lines.append("")

    # Fee Rate Distribution
    fee_stats = summary.get('fee_rate_stats', {})
    lines.append("### Fee Rate Distribution")
    lines.append("")
    lines.append("| Metric | Value (sat/vB) |")
    lines.append("|---|---|")
    lines.append(f"| Minimum | {fee_stats.get('min_sat_vb', 0)} |")
    lines.append(f"| Maximum | {fee_stats.get('max_sat_vb', 0)} |")
    lines.append(f"| Median | {fee_stats.get('median_sat_vb', 0)} |")
    lines.append(f"| Mean | {fee_stats.get('mean_sat_vb', 0)} |")
    lines.append("")

    # Script Type Breakdown
    script_dist = summary.get('script_type_distribution', {})
    lines.append("### Script Type Breakdown")
    lines.append("")
    lines.append("| Script Type | Count | Percentage |")
    lines.append("|---|---|---|")
    total_outputs = sum(script_dist.values()) if script_dist else 0
    for stype in sorted(script_dist.keys(), key=lambda x: -script_dist[x]):
        count = script_dist[stype]
        pct = _pct(count, total_outputs)
        lines.append(f"| {stype} | {count} | {pct}% |")
    lines.append("")

    # Classification Summary (file-level)
    class_dist = summary.get('classification_distribution', {})
    if class_dist:
        lines.append("### Transaction Classification Summary")
        lines.append("")
        lines.append("| Classification | Count | Percentage |")
        lines.append("|---|---|---|")
        for cls in sorted(class_dist.keys(), key=lambda x: -class_dist[x]):
            count = class_dist[cls]
            pct = _pct(count, total_txs)
            lines.append(f"| {cls} | {count} | {pct}% |")
        lines.append("")

    # Heuristic Summary
    lines.append("### Heuristic Coverage")
    lines.append("")
    h_counts = summary.get('heuristic_detection_counts', {})
    lines.append("| Heuristic | ID | Detections |")
    lines.append("|---|---|---|")
    for h_id in heuristics:
        count = h_counts.get(h_id, 0)
        lines.append(f"| {_heuristic_name(h_id)} | `{h_id}` | {count} |")
    lines.append("")

    # === Per-Block Sections ===
    for i, block in enumerate(blocks):
        block_hash = block.get('block_hash', 'unknown')
        block_height = block.get('block_height', 'N/A')
        tx_count = block.get('tx_count', 0)
        block_summary = block.get('analysis_summary', {})
        block_fee = block_summary.get('fee_rate_stats', {})
        block_flagged = block_summary.get('flagged_transactions', 0)
        block_script_dist = block_summary.get('script_type_distribution', {})
        block_timestamp = block.get('timestamp')

        lines.append(f"## Block {i + 1}: Height {block_height}")
        lines.append("")
        lines.append(f"| Property | Value |")
        lines.append(f"|---|---|")
        lines.append(f"| Block Hash | `{block_hash}` |")
        lines.append(f"| Block Height | {block_height} |")
        if block_timestamp:
            ts_str = datetime.fromtimestamp(block_timestamp, tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
            lines.append(f"| Timestamp | {ts_str} |")
        lines.append(f"| Transaction Count | {tx_count} |")
        lines.append(f"| Flagged Transactions | {block_flagged} ({_pct(block_flagged, tx_count)}%) |")
        lines.append(f"| Min Fee Rate | {block_fee.get('min_sat_vb', 0)} sat/vB |")
        lines.append(f"| Max Fee Rate | {block_fee.get('max_sat_vb', 0)} sat/vB |")
        lines.append(f"| Median Fee Rate | {block_fee.get('median_sat_vb', 0)} sat/vB |")
        lines.append(f"| Mean Fee Rate | {block_fee.get('mean_sat_vb', 0)} sat/vB |")
        lines.append("")

        # Per-block script type distribution
        if block_script_dist:
            lines.append(f"### Script Types (Block {i + 1})")
            lines.append("")
            lines.append("| Script Type | Count |")
            lines.append("|---|---|")
            for stype in sorted(block_script_dist.keys(), key=lambda x: -block_script_dist[x]):
                lines.append(f"| {stype} | {block_script_dist[stype]} |")
            lines.append("")

        # Heuristic findings — use analysis_summary data (works for ALL blocks)
        block_h_counts = block_summary.get('heuristic_detection_counts', {})
        block_heuristics = block_summary.get('heuristics_applied', [])
        if block_heuristics:
            lines.append(f"### Heuristic Findings (Block {i + 1})")
            lines.append("")
            lines.append("| Heuristic | Detections | Percentage |")
            lines.append("|---|---|---|")
            for h_id in block_heuristics:
                count = block_h_counts.get(h_id, 0)
                pct = _pct(count, tx_count)
                lines.append(f"| {_heuristic_name(h_id)} | {count} | {pct}% |")
            lines.append("")

        # Classification breakdown — use analysis_summary data (works for ALL blocks)
        block_class_dist = block_summary.get('classification_distribution', {})
        if block_class_dist:
            lines.append(f"### Transaction Classifications (Block {i + 1})")
            lines.append("")
            lines.append("| Classification | Count | Percentage |")
            lines.append("|---|---|---|")
            for cls in sorted(block_class_dist.keys(), key=lambda x: -block_class_dist[x]):
                count = block_class_dist[cls]
                pct = _pct(count, tx_count)
                lines.append(f"| {cls} | {count} | {pct}% |")
            lines.append("")

        # Notable transactions — only available for blocks with tx_entries
        txs = block.get('transactions', [])
        if txs:
            notable = _find_notable_transactions(txs)
            if notable:
                lines.append(f"### Notable Transactions (Block {i + 1})")
                lines.append("")
                for note in notable[:15]:  # Limit to 15
                    lines.append(f"- **`{note['txid'][:16]}...`** — {note['reason']}")
                lines.append("")

    # === Footer ===
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by Sherlock Chain Analysis Engine*")
    lines.append("")

    return '\n'.join(lines)


def _pct(part, total):
    """Compute percentage rounded to 1 decimal."""
    if total == 0:
        return "0.0"
    return f"{(part / total * 100):.1f}"


def _heuristic_name(h_id):
    """Human-readable name for a heuristic ID."""
    names = {
        'cioh': 'Common Input Ownership',
        'change_detection': 'Change Detection',
        'address_reuse': 'Address Reuse',
        'coinjoin': 'CoinJoin Detection',
        'consolidation': 'Consolidation Detection',
        'self_transfer': 'Self-Transfer Detection',
        'peeling_chain': 'Peeling Chain Detection',
        'op_return': 'OP_RETURN Analysis',
        'round_number_payment': 'Round Number Payment',
    }
    return names.get(h_id, h_id)


def _find_notable_transactions(tx_entries):
    """Find notable transactions for the report."""
    notable = []
    for tx_entry in tx_entries:
        txid = tx_entry.get('txid', '')
        cls = tx_entry.get('classification', 'unknown')
        heuristics = tx_entry.get('heuristics', {})

        if cls == 'coinjoin':
            cj = heuristics.get('coinjoin', {})
            eq_count = cj.get('equal_output_count', 0)
            notable.append({
                'txid': txid,
                'reason': f"CoinJoin detected — {eq_count} equal-value outputs"
            })
        elif cls == 'consolidation':
            cons = heuristics.get('consolidation', {})
            in_count = cons.get('input_count', 0)
            notable.append({
                'txid': txid,
                'reason': f"Consolidation — {in_count} inputs merged"
            })
        elif cls == 'self_transfer':
            st = heuristics.get('self_transfer', {})
            dom_type = st.get('dominant_type', 'unknown')
            notable.append({
                'txid': txid,
                'reason': f"Self-transfer detected — all outputs {dom_type}"
            })
        elif cls == 'batch_payment':
            out_count = tx_entry.get('output_count', 0)
            notable.append({
                'txid': txid,
                'reason': f"Batch payment — {out_count} outputs to multiple recipients"
            })
        elif heuristics.get('peeling_chain', {}).get('detected', False):
            pc = heuristics['peeling_chain']
            ratio = pc.get('ratio', 0)
            notable.append({
                'txid': txid,
                'reason': f"Peeling chain pattern — {ratio}:1 output ratio"
            })
        elif heuristics.get('address_reuse', {}).get('detected', False):
            ar = heuristics['address_reuse']
            overlap = ar.get('input_output_overlap', 0)
            cross = ar.get('cross_tx_reuse_count', 0)
            detail = []
            if overlap:
                detail.append(f"{overlap} input-output overlap")
            if cross:
                detail.append(f"{cross} cross-tx reuse")
            notable.append({
                'txid': txid,
                'reason': f"Address reuse — {', '.join(detail) if detail else 'privacy risk'}"
            })
        elif heuristics.get('op_return', {}).get('detected', False):
            op = heuristics.get('op_return', {})
            outputs = op.get('outputs', [])
            if outputs:
                protocol = outputs[0].get('protocol', 'unknown')
                notable.append({
                    'txid': txid,
                    'reason': f"OP_RETURN data — protocol: {protocol}"
                })

    return notable


def write_markdown(content, filepath):
    """Write the Markdown report to a file."""
    with open(filepath, 'w') as f:
        f.write(content)
